version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: Nestjs
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
